title: "Jak jsem dělal domácí server"
description: "Osobní technická série o stavbě a provozu domácího serveru"
locale: cs-CZ
url: "https://maly.github.io"   # změň po nasazení
baseurl: "/homeserver-doc"

theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes@4.27.3"

minimal_mistakes_skin: "plum"
breadcrumbs: true


markdown: kramdown

# Kolekce pro sérii
collections:
  homeserver:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "homeserver"
    values:
      layout: single
      author_profile: false
      read_time: true
      share: false
      comments: false
      toc: true
      toc_sticky: true

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Nastavení archivu (volitelné pro /tags apod.)
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /kategorie/:name/
    tag: /tag/:name/

# RSS jen pro kolekci homeserver (volitelné)
feed:
  collections:
    - homeserver
    
author:
  name: "Martin Malý"
  avatar: "/assets/images/bio.jpg"
  bio: "Manažer, programátor a autor."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maly"    